# Generated by Django 5.1.6 on 2026-03-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbxsync', '0010_zabbixhostinterface_snmp_pushcommunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixhostinterface',
            name='snmp_max_repetitions',
            field=models.PositiveBigIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='zabbixserver',
            name='sync_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zabbixserverassignment',
            name='sync_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
