# Generated by Django 5.1.6 on 2026-03-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbxsync', '0011_zabbixhostinterface_max_repetitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixserver',
            name='skip_version_check',
            field=models.BooleanField(default=False),
        ),
    ]
